import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class EnergyConsumption {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column()
  tenant_id!: number;

  @Column("float")
  kWh_used!: number;

  @Column({ type: "timestamp" })
  timestamp!: Date;
}
// This entity represents energy consumption data in the database. It includes the following fields:
// - id: A unique identifier for the energy consumption record, automatically generated by the database.
// - tenant_id: The ID of the tenant associated with the energy consumption record, stored as a number.
